USE [master]
GO

/****** Object:  Database [RetailDatabase]    Script Date: 29-11-2016 00:45:33 ******/
CREATE DATABASE [RetailDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RetailDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\RetailDatabase.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RetailDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\RetailDatabase_log.ldf' , SIZE = 388544KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RetailDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RetailDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RetailDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RetailDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RetailDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RetailDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RetailDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [RetailDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RetailDatabase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RetailDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RetailDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RetailDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RetailDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RetailDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RetailDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RetailDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RetailDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RetailDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RetailDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RetailDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RetailDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RetailDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RetailDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RetailDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RetailDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RetailDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [RetailDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [RetailDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RetailDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RetailDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RetailDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RetailDatabase] SET  READ_WRITE 
GO


